### ISSUE TITLE
Using this library with .NET framework 4.8 and Visual Studio 2017

### ISSUE THREAD

**Issue by valgen** [51Degrees/device-detection-dotnet#13]
Hi,

I would like to use this library in a WEB application with .NET framework 4.8 and Visual Studio 2017. Is it possible?

Unfortunately I get an exception when I try to execute this code:
`new DeviceDetectionPipelineBuilder().UseOnPremise(HostingEnvironment.MapPath("~/App_Data/51Degrees-LiteV4.1.hash"), null, false).SetPerformanceProfile(PerformanceProfiles.LowMemory).Build()`

This is the exception (including the inner exceptions):

**The type initializer for 'FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE' threw an exception.**
_at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.new_ConfigHashSwig()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.ConfigHashSwig..ctor()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Wrappers.SwigFactory.<>c.<.ctor>b__4_3()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.get_SwigConfig()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements.DeviceDetectionHashEngineBuilder.SetPerformanceProfile(PerformanceProfiles profile)
   at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.ConfigureAndBuild[TBuilder,TEngine](OnPremiseDeviceDetectionEngineBuilderBase`2 builder)
   at FiftyOne.DeviceDetection.DeviceDetectionOnPremisePipelineBuilder.Build()
   at project1.Models.FiftyOneDegrees.GetDevice() in C:\Users\user1\source\Workspaces\workspace\project1\project1\Models\FiftyOneDegrees.cs:line 151_

**The type initializer for 'SWIGExceptionHelper' threw an exception.**
_at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper..ctor()
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE..cctor()_

**An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)**
_at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_DeviceDetectionHashEngineModule(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Interop.DeviceDetectionHashEngineModulePINVOKE.SWIGExceptionHelper..cctor()_

Thanks
valgen

**Comment by Steve51D** [comment]
Hi @valgen,

The Pipeline API [supports](http://51degrees.com/documentation/4.3/_info__version_support.html) .NET Framework 4.6.2 and above, so you should be fine from that point of view.

The on-premise device detection uses a native binary, which must match the target environment.
Currently our on-premise package contains binaries for both x86 and x64. (You can see these in the runtimes folder [within the package](https://nuget.info/packages/FiftyOne.DeviceDetection.Hash.Engine.OnPremise/4.3.5)).

This error (**An attempt was made to load a program with an incorrect format**) generally means that the system is trying to load a 64-bit assembly into a 32-bit process or vice/versa.

The package will load the x64 binary if your solution is targeting 'x64' and the x86 binary if it's targeting 'x86' or 'AnyCPU'.

Can you let us know which platform you're targeting?
Also, can you try changing it and see if that changes the situation?
Finally, a minimal test solution that reproduces the problem would be helpful.

Thanks,
Steve.

**Comment by valgen** [comment]
Hi @Steve51D,

Thank you for the prompt reply.

My project Active Platform was set to "Any CPU".

So I checked your NuGet package and found out that **if '$(Platform)' == 'AnyCPU'** you default to the 'x86' native binary.

```
  <ItemGroup Condition=" '$(Platform)' == 'x64' ">
    <Content Include="$(MSBuildThisFileDirectory)..\runtimes\win-x64\native\FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll</Link>
    </Content>
  </ItemGroup>

  <ItemGroup Condition=" '$(Platform)' == 'x86' OR '$(Platform)' == 'AnyCPU' ">
    <Content Include="$(MSBuildThisFileDirectory)..\runtimes\win-x86\native\FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll</Link>
    </Content>
  </ItemGroup>
```

So now I've changed my project to target 'x64' and the exception has gone.

Thanks
valgen

**Comment by Steve51D** [comment]
That's good to know thanks.
We'll be taking a look at the AnyCPU setting to see if we should handle it differently.

**Comment by valgen** [comment]
Hi @Steve51D,

I've discovered another possible issue.

When I publish from visual Studio the following **dll** gets copied to the webroot (same level as the web.config) as well as to the **bin** folder:
`FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll`

Obviously it should be copied just to the **bin** folder. I wonder if you could fix this behaviour.

Thanks
valgen
