### ISSUE TITLE
Native dll gets copied to the webroot as well as to the bin folder

### ISSUE THREAD

**Issue by Steve51D** [51Degrees/device-detection-dotnet#15]
I've discovered another possible issue.

When I publish from visual Studio the following **dll** gets copied to the webroot (same level as the web.config) as well as to the **bin** folder:
`FiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll`

Obviously it should be copied just to the **bin** folder. I wonder if you could fix this behaviour.

Thanks
valgen

_Originally posted by @valgen in https://github.com/51Degrees/device-detection-dotnet/issues/13#issuecomment-949080974_

**Comment by fatima51Degrees** [comment]
Hi @valgen,

This issue is now resolved in the latest release [Version 4.3.9](https://github.com/51Degrees/device-detection-dotnet/releases/tag/4.3.9) of device-detection-dotnet.
