### ISSUE TITLE
Crash when using a cloud resource key that includes the SupportedI/O property

### ISSUE THREAD

**Issue by Steve51D** [51Degrees/device-detection-dotnet#18]
To reproduce:
- Create a [new resource key](https://configure.51degrees.com/) that includes the `Supported I/O` property.
- Create a new .NET project 
- Add a reference to FfityOne.DeviceDetection
- Use the DeviceDetectionPipelineBuilder to create a pipeline using the cloud service, passing the resource key created above.

When creating the pipeline, the program will crash with the following error:
```
FiftyOne.Pipeline.Core.Exceptions.PipelineException: Unable to determine the type associated with this property. No c# property found matching definition DeviceDataCloud.SupportedI/O and json type 'Array' is not mapped.
```

This is because the cloud service property meta-data (accessible at https://cloud.51degrees.com/api/v4/accessibleproperties?resource=[RESOURCE_KEY]) only gives the json 'type' of each property.
For strongly-typed languages, we need to translate this into the real type. This is generally simple, but presents a problem for properties like `Supported I/O` where the json type is `Array`.

For .NET, we need to translate this into `IAsectPropertyValue<IReadOnlyList<string>>`. Rather than making any assumptions, we use the name of the property from the meta-data and reflection in order to get the type from the associated strongly-typed property.

In this case, that doesn't work because the name in the meta-data - `SupportedI/O` does not match the name of the property in code `SupportedIO`.

This will be fixed in a future release. 
If you experience this problem in the meantime, then please let us know by commenting below.

**Comment by ben51degrees** [comment]
Closed with version [4.3.12](https://github.com/51Degrees/device-detection-dotnet/releases/tag/4.3.12).
