### ISSUE TITLE
How Do I Use 51 Degrees with a Razor Page?

### ISSUE THREAD

**Issue by PostAlmostAnything** [51Degrees/device-detection-dotnet#19]
Nevermind, found different solution.

**Comment by tungntpham** [comment]
Hi @PostAlmostAnything,

Our 51Degrees solution can be used with a Razor Page in a similar manner to AspNet Core MVC. There is an example of how it is used with AspNet Core MVC which you can find [here](http://51degrees.com/documentation/4.3/_examples__device_detection__web_integration__examples.html).

For other examples, please see [documentation](http://51degrees.com/documentation/4.3/index.html).

I have also attached 2 zipped projects for On-premise and Cloud solutions separately here, to demonstrate how it can be used with Razor Pages.
- Cloud: 
  - [51DegreesCloudRazorPages.zip](https://github.com/51Degrees/device-detection-dotnet/files/7815289/51DegreesCloudRazorPages.zip)
  - Please obtain a resource key from [here](https://configure.51degrees.com/) and update the following line in the `appsettings.json`
    -  `"ResourceKey": "!!ENTER_YOUR_RESOURCE_KEY_HERE!!"`
- On-premise:
  - [51DegreesOnPremiseRazorPages.zip](https://github.com/51Degrees/device-detection-dotnet/files/7815290/51DegreesOnPremiseRazorPages.zip)
  - Please obtain a free Lite data file from [here](https://github.com/51Degrees/device-detection-data) or from our [pricing page](http://51degrees.com/pricing) and place it in the root directory of the project.

You might need to run `dotnet restore` in the root directory to get all dependencies packages.

The main difference between RazorPage setup and MVC is that each RazorPage has its own model. Thus, unlike the `MVC` example where `Device` data is obtained in the `Controller` before passing to the `View`, the `Device` data is obtained in the page model and make available to the page when serving a request.

Example of a page model `Index.cshtml.cs` of page `Index.cshtml`
```
using FiftyOne.Pipeline.Web.Services;
using FiftyOne.DeviceDetection;
using FiftyOne.Pipeline.Engines.Services;
using FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements;

namespace _51DegreesRazorPages.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public IDeviceData Data { get; set; }

        private IFlowDataProvider _flow;

        // `flow` object is injected here
        public IndexModel(ILogger<IndexModel> logger, IFlowDataProvider flow)
        {
            _logger = logger;
            _flow = flow;
        }

        // On 'GET` obtain `Device Data`
        public void OnGet()
        {
            Data = _flow.GetFlowData().Get<IDeviceData>();
        }
    }
}
```

Example of how `Device Data` can be accessed in page `index.cshtml`
```
@page
@model IndexModel
@{
    ViewData["Title"] = "Device detection example";
    var platformVendor = Model.Data.PlatformVendor;
    var platformName = Model.Data.PlatformName;
    var platformVersion = Model.Data.PlatformVersion;
    var browserVendor = Model.Data.BrowserVendor;
    var browserName = Model.Data.BrowserName;
    var browserVersion = Model.Data.BrowserVersion;
}

<h2>Example</h2>

<p>
    Platform Vendor: @(platformVendor.HasValue ? platformVendor.Value : $"Unknown ({platformVendor.NoValueMessage})")<br />
    Platform Name: @(platformName.HasValue ? platformName.Value : $"Unknown ({platformName.NoValueMessage})")<br />
    Platform Version: @(platformVersion.HasValue ? platformVersion.Value : $"Unknown ({platformVersion.NoValueMessage})")<br />
    Browser Vendor: @(browserVendor.HasValue ? browserVendor.Value : $"Unknown ({browserVendor.NoValueMessage})")<br />
    Browser Name: @(browserName.HasValue ? browserName.Value : $"Unknown ({browserName.NoValueMessage})")<br />
    Browser Version: @(browserVersion.HasValue ? browserVersion.Value : $"Unknown ({browserVersion.NoValueMessage})")
</p>

@await Component.InvokeAsync("FiftyOneJS")
```

The rest is similar as described in the AspNet Core MVC example, where you need to do the followings. More details can be found the MVC example:
- update `appsettings.json` to configure `Device Detection` engine.
- In Startup.cs
  - Add 51Degrees services in `ConfigureServices` method.
  - Use 51Degrees service in `Configure` method.

If you encounter `Missing Property Exception`, please make sure that the properties are available with your resource key or with your data file.

Kind regards,
Tung.
