### ISSUE TITLE
Information provided through some client hints seems to be ignored

### ISSUE THREAD

**Issue by Martijn-vd-H** [51Degrees/device-detection-dotnet#20]
I've noticed some information in the client hints seems to be ignored. When I provide the browser version with the client hint `sec-ch-ua-full-version`, for example `97.0.4692.99` I can only retrieve `97` from the DeviceData. What happens to the minor version?
What's more is that I can provide information about the bitness or architecture with the client hints `sec-ch-ua-bitness: 64` and `sec-ch-ua-arch: x86` which I'm not seeing back in any way in the device data. I'd expect some assumptions can be made about the hardware or device with this information.

**Comment by Steve51D** [comment]
Hi @Martijn-vd-H,

We generally don't make use of the value from the `sec-ch-ua-full-version` header (although this isn't always true). This is simply because, in general, none of the properties we return would be any different when it is taken into account.

`sec-ch-ua-bitness` and `sec-ch-ua-arch` are also not relevant in most cases for the same reasons.

If knowing these values (full version, OS bitness and processor architecture) or something derived from them would be useful to you, then you can contact our commercial team to discuss adding new properties for them: support@51degrees.com.

**Comment by Martijn-vd-H** [comment]
Hi Steve, thank you for your answer. I can see that this information isn't all that valuable. However, there is still one piece of information that I'd expect to see back in the parsed results. I'm talking about the operating system. I'll give a few examples:

If I pass the following user agent string `Mozilla/5.0 (Linux; Android 11; DN2103) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Mobile Safari/537.36` with the following client hints (among others):

- `sec-ch-ua-platform`, `"Android"`
- `sec-ch-ua-model`, `"DN2103"`
- `sec-ch-ua-platform-version`,  `"11.0.0"`

The PlatformName and the PlaformVersion in the device data returns "Unknown", while I expected Android 11, which is clear in both the user agent string and the client hints. If I remove the quotes in the strings, instead of feeding the component exactly the data as I receive it from the browser I get `iOS` as platform name. This doesn't seem right. It does however recognize the HardwareModel and Family correctly in both instances.

Another example with the Edge browser and the platform version:

User agent string: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43`
Client hints: 
  - `sec-ch-ua-platform-version`, `10.0.0`
  - `sec-ch-ua-platform`, `"Windows"`

The PlatformName returns `Windows NT` and PlatformVersion `Unknown`.

What's the reason behind this?

**Comment by Steve51D** [comment]
Thanks for the update Martijn, that is helpful.
The problem in these cases is that the current data file only has limited training data for client hint headers. 
We are currently working to improve this internally, and hope to have a data file with more complete support for client hints in the near future.

The intention is that once this work is complete, you will just be able to provide all the values unmodified, as you have in these examples, and you'll get the correct results back.
I'll update this issue once we have such a data file available.

**Comment by Martijn-vd-H** [comment]
Thanks Steve. I appreciate it. 
Looking forward to the update.

**Comment by Steve51D** [comment]
@Martijn-vd-H One thing to mention if you just want to test it, is that the current data file will definitely detect Windows 11 correctly. You can check this by using the following values:

- `sec-ch-ua-platform` = `"Windows"`
- `sec-ch-ua-platform-version` = `14.0.0`

**Comment by Martijn-vd-H** [comment]
@Steve51D Thanks. This is indeed correctly parsed. I'll add it to my test data.

**Comment by Steve51D** [comment]
Hi @Martijn-vd-H, 

The latest API and data files enable full detection from UA-CH values.
Can you let us know if you are still seeing any issues with this?

Many thanks.

**Comment by Martijn-vd-H** [comment]
Hi Steve,

Thank you for the update! I was on vacation and have to catch up on some other things. 
I'll look into it a little later and let you know the results!

**Comment by Steve51D** [comment]
Closing this for now. If you are still seeing any issues then please let us know.
