### ISSUE TITLE
How to provide client hint evidence from the Javascript API 

### ISSUE THREAD

**Issue by Martijn-vd-H** [51Degrees/device-detection-dotnet#21]
Hello,

We've found out that the Javascript API exposes a call that will return low- and high entropy user agent client hints without needing `Accept-CH` and `Permission-Policy` headers. However, the key names and formatting of the values is a bit different than what we receive through response headers. I receive the following from Google Chrome with the `navigator.userAgentData.getHighEntropyValues` call:

- brands	[{"brand":" Not A;Brand","version":"99"},
          {"brand":"Chromium","version":"98"},
          {"brand":"Google Chrome","version":"98"}]
- mobile: false
- platform: Windows
- platformVersion: 10.0.0
- architecture: x86
- bitness: 64
- model: empty
- uaFullVersion: 98.0.4758.102

Whereas response headers present data like this:

- Sec-CH-UA: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
- Sec-CH-UA-Platform: "Windows"
- Sec-CH-UA-Mobile": ?0
- Sec-CH-UA-Full-Version: "98.0.4758.102"
- Sec-CH-UA-Platform-Version: "10.0.0"
- Sec-CH-UA-Arch: "x86"
- Sec-CH-UA-Bitness: "64"
- Sec-CH-UA-Model: ""

Notice the difference in key names, formatting of brands where the JS API uses newline separators and the response headers a ";", the usage of quotes etc.

How should we provide the evidence we receive from the JS API? Should we convert it to the response header naming and formatting, or use different prefixes when adding it to the flowdata?

Looking forward to your response.

Best regards,
Martijn

**Comment by Steve51D** [comment]
Hi Martijn,

Unfortunately, we don't yet have a way to accept the raw values from the JavaScript API. You'll need to convert them to the same format as the HTTP headers and then pass them as if the values had come from those headers.

In the longer term, we may look at a specific mechanism to pass the raw values, but that's not made it onto the schedule yet.

**Comment by Martijn-vd-H** [comment]
Hi Steve, 

That's unfortunate.
Nonetheless, thank you for the quick and clear reply. I know what to do. 

Have nice day.
