### ISSUE TITLE
NON-Core asp.net (full dot-net) example

### ISSUE THREAD

**Issue by OMortensen** [51Degrees/device-detection-dotnet#22]
Where can I find a dot-net library (not dot-net Core) example that sets Request.Browser["IsMobile"] for an asp.net IIS web site project?
The upgrade instruction on the 51 degrees website contains code for Global.asax.cs that I cannot get to compile. The errors are:
1. The type or namespace name 'JavaScriptBuilderElement' could not be found (are you missing a using directive or an assembly reference?)
2. The type or namespace name 'JsonBuilderElement' could not be found (are you missing....
3. The type or namespace name 'DeviceDetectionHashEngineBuilder' could not be found (are you missing....

We are upgrading from version 3.x for an asp.net web site project (not a web application project). I followed the directions at: https://51degrees.com/documentation/4.4/_device_detection__migration_guides_51_degrees_v3.html

**Comment by Steve51D** [comment]
Hi @OMortensen, 

We have a few items that we need to address around .NET Framework integration. One of which is a complete web example, so I'm afraid I can't direct you to one at the moment. Hopefully we can resolve the problem you're experiencing though.

I'm assuming the errors you're mentioning are coming from the lines to load the assemblies. E.g.

```
AppDomain.CurrentDomain.Load(typeof(JavaScriptBuilderElement).Assembly.GetName());
```

If that's correct, then there are two possible causes I can think of:
1. The relevant assembly has not been added as a NuGet package. Make sure you have NuGet packages `FiftyOne.DeviceDetection` and `FiftyOne.Pipeline.Web` added to the project.
2. `using` statements have not been added in global.asax for the required namespaces. Make sure the following are present the top of the file:

```
using FiftyOne.DeviceDetection.Hash.Engine.OnPremise.FlowElements
using FiftyOne.Pipeline.Engines.FiftyOne.FlowElements
using FiftyOne.Pipeline.JavaScriptBuilder.FlowElement
using FiftyOne.Pipeline.JsonBuilder.FlowElement
```

Please let me know how it goes. Thanks.

**Comment by Steve51D** [comment]
Documentation has now been updated. There is also an ASP.NET Framework example available.
