### ISSUE TITLE
CentOS 7 support

### ISSUE THREAD

**Issue by damiankaminski** [51Degrees/device-detection-dotnet#23]
Right now `libFiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll` depends on `glibc` 2.27.  Unfortunately, CentOS 7 supports only `glibc` 2.17. Would it be possible to compile device detection library with an older `glibc`?

```bash
$ ldd runtimes/linux-x64/native/libFiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll 
runtimes/linux-x64/native/libFiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by runtimes/linux-x64/native/libFiftyOne.DeviceDetection.Hash.Engine.OnPremise.Native.dll)
	linux-vdso.so.1 =>  (0x00007ffea0f2e000)
	libatomic.so.1 => /lib64/libatomic.so.1 (0x00007f2745131000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f2744e2f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2744c13000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2744845000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2745720000)
```

**Comment by ben51degrees** [comment]
Hi @damiankaminski ,
When using systems that we do not support through the NuGet package directly, we recommend compiling the native binaries yourself on the target system.
There are some prerequisutes in the readme which will need to be installed. Then you can run the `PreBuild.sh` to build the binaries.
While you can use the cloned project directly, you should actually be able to continue to use the NuGet pacakge, but copy the binaries into your `bin` directory. This will be scanned before `runtimes/linux-....` when attempting to load the binary.
Thanks,
Ben

**Comment by ben51degrees** [comment]
Hi @damiankaminski ,
As we have not heard back, I'll close this issue.
If you are still having problems, feel free to reopen.
Thanks,
Ben
