### ISSUE TITLE
Cannot disable JavascriptBuilderElement and JsonBuilderElement 

### ISSUE THREAD

**Issue by Steve51D** [51Degrees/device-detection-dotnet#28]
When using server-side Apple detection, it may be desirable to disable `JavaScriptBuilderElement` and `JsonBuilderElement`. 
These elements add a significant performance penalty and are added to the pipeline by default if using the web integration package. However, they're not needed if server-side Apple detection is being used.

In the future, we plan to address this by improving the performance of these elements, adding more configuration options to limit the properties they include, and allow them to be fully disabled if needed.

For the moment, the only way to manage this is with the following workaround:

1. Create a custom element that just sets FlowData.Stop = true. There is [an example of this](https://github.com/51Degrees/pipeline-dotnet/blob/master/Tests/FiftyOne.Pipeline.Core.Tests/HelperClasses/StopElement.cs) in our test suite. 
2. You'll also need a 'builder' class for this element. It just needs to contain a Build method that takes no parameters and returns a new instance of the StopElement similar to [this](https://github.com/51Degrees/pipeline-dotnet/blob/master/Tests/FiftyOne.Pipeline.Core.Tests/HelperClasses/MultiplyByElementBuilder.cs).
3. Modify your configuration to add the StopElement after all required elements and before the ones you want to skip. For example, to skip `JavaScriptBuilderElement` and `JsonBuilderElement`:
```
{
  "Elements": [
    {
      "BuilderName": "AppleProfileEngineBuilder",
      "BuildParameters": {
        ...
      }
    },
    {
      "BuilderName": "DeviceDetectionHashEngineBuilder",
      "BuildParameters": {
        ...
      }
    },
    {
      "BuilderName": "SetHeadersElementBuilder"
    },
    {
      "BuilderName": "StopElementBuilder"
    },
    {
      "BuilderName": "JsonBuilderElementBuilder"
    },
    {
      "BuilderName": "JavaScriptBuilderElementBuilder",
      "BuildParameters": {
        ...
      }
    }
  ]
}
```

**Comment by ben51degrees** [comment]
This can now be disabled by setting the `ClientSideEvidenceEnabled` option. See configuration in [web example](http://51degrees.com/documentation/4.4/_examples__device_detection__getting_started__web__on_premise.html) for how this is used.
