### ISSUE TITLE
Getting error stating NuGet pulled files not being Strong Named when using Strong Name Key signing

### ISSUE THREAD

**Issue by Sara51D** [51Degrees/device-detection-dotnet#29]
When using the Strong Name Key signing the following error messages about the NuGet pulled files not being Strong Named are seen:

(0): error CS1577: Assembly generation failed -- Referenced assembly 'FiftyOne.Pipeline.CloudRequestEngine' does not have a strong name

(0): error CS1577: Assembly generation failed -- Referenced assembly 'FiftyOne.DeviceDetection.Cloud' does not have a strong name

(0): error CS1577: Assembly generation failed -- Referenced assembly 'FiftyOne.Pipeline.JavaScriptBuilderElement' does not have a strong name

(0): error CS1577: Assembly generation failed -- Referenced assembly 'FiftyOne.Pipeline.JsonBuilder' does not have a strong name

(0): error CS1577: Assembly generation failed -- Referenced assembly 'FiftyOne.Pipeline.Engines.FiftyOne' does not have a strong name

**Comment by Sara51D** [comment]
As the NuGet packages are signed, have requested additional information.
The specific step generating the error message is:

set WebCompiler=C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler
"%WebCompiler%" -p "%SlnDir%\WebSite" -v / "%OutputDir%" -fixednames -f -u -keyfile "C:\CodeSigning\website.snk"

**Comment by jwrosewell** [comment]
We've confirmed we're signing the packages in the way we've always done.

Please could you try using the example for .NET Framework and advise if the error you're experiencing is present there?

The on-premise example is [here](https://github.com/51Degrees/device-detection-dotnet/tree/master/Examples/OnPremise/Framework-Web).

The cloud example is [here](https://github.com/51Degrees/device-detection-dotnet/tree/master/Examples/Cloud/Framework-Web).

**Comment by justadreamer** [comment]
@drasmart could you please:
1. try to reproduce the errors original author had
2. check how complex would it be to add assembly signing and whether it would solve the original problem.  thank you.

**Comment by drasmart** [comment]
## Error replication

Clean build of `FiftyOne.Pipeline.Engines` with strong name

```ps
dotnet build .\FiftyOne.Pipeline.Engines\FiftyOne.Pipeline.Engines.csproj --no-incremental
```

Produces 3 errors:

```text
Build FAILED.

CSC : error CS8002: Referenced assembly 'FiftyOne.Pipeline.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\Projects\Work\pipeline-dotnet\FiftyOne.Pipeline.Engines\FiftyOne.Pipel
ine.Engines.csproj]
CSC : error CS8002: Referenced assembly 'FiftyOne.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\Projects\Work\pipeline-dotnet\FiftyOne.Pipeline.Engines\FiftyOne.Pipeline.Eng
ines.csproj]
CSC : error CS8002: Referenced assembly 'FiftyOne.Caching, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\Projects\Work\pipeline-dotnet\FiftyOne.Pipeline.Engines\FiftyOne.Pipeline.En
gines.csproj]
    0 Warning(s)
    3 Error(s)
```

If `FiftyOne.Pipeline.Core` is also strongly named (and re-built) only 2 error remain:

```text
Build FAILED.

CSC : error CS8002: Referenced assembly 'FiftyOne.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\Projects\Work\pipeline-dotnet\FiftyOne.Pipeline.Engines\FiftyOne.Pipeline.Eng
ines.csproj]
CSC : error CS8002: Referenced assembly 'FiftyOne.Caching, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [C:\Projects\Work\pipeline-dotnet\FiftyOne.Pipeline.Engines\FiftyOne.Pipeline.En
gines.csproj]
    0 Warning(s)
    2 Error(s)
```

## Changes to enable strong names

#### 1. Create key pair file

```ps
sn -k keypair.snk
```

It should be checked into git -- explained why later.

#### 2. Extract public key into separate (temporary) file

```ps
sn -p keypair.snk public.snk
```

#### 3. Print public key

```ps
sn -tp public.snk
```

#### 4. Add public key to [[InternalsVisibleTo](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-8.0#examples)] attributes

in placed like

```cs
[assembly: InternalsVisibleTo("FiftyOne.Pipeline.Core.Tests")]
[assembly: InternalsVisibleTo("FiftyOne.Pipeline.Engines.TestHelpers")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
```

^ from [[AssemblyInfo.cs](https://github.com/51Degrees/pipeline-dotnet/blob/main/FiftyOne.Pipeline.Core/Properties/AssemblyInfo.cs#L34-L36)].

#### 5. Enable Strong Name in project settings

Follow [[Create and sign an assembly with a strong name by using Visual Studio](https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name#create-and-sign-an-assembly-with-a-strong-name-by-using-visual-studio)].

## Downsides

Below are excerpts from [[I really, really need to strong-name, what kinds of issues will I run into?](https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md#2-i-really-really-need-to-strong-name-what-kinds-of-issues-will-i-run-into)].

#### - Binding Policy

> binding policy [...] forces, by default, an exact match between reference and version, and requires developers to author complex [binding redirects](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/bindingredirect-element) when they don't.

#### - Virality

> Once you've strong-named an assembly, you can only statically reference other strong-named assemblies.

It is yet unclear if any dependencies don't have Strong Names.

#### - No drop-in replacement

> Developers are unable to build to their own version of the library and then use it as a drop-in replacement without recompiling _all_ consuming libraries up stack to pick up the new identity.

### Expected/Recommended mitigation procedural changes

> CONSIDER adding the strong naming key to your source control system.
> DO NOT add, remove, or change the strong naming key.

- ^ these 2 aren't critical but bring up a question whether each repo should have a dedicated key pair, or all of them would share the same `.snk` file.

> CONSIDER incrementing the assembly version on only major version changes to help users reduce binding redirects, and how often they're updated.

- ^ which might negate the efforts of `nightly-package-update` scripts.

For more details see [[Strong naming](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries)].

**Comment by justadreamer** [comment]
let's add a paragraph to the README on why we don't strong name assemblies
