### ISSUE TITLE
PropertyMissingException

### ISSUE THREAD

**Issue by kiro64** [51Degrees/device-detection-dotnet#4]
Hello, i try to run the Example project `DeviceDetectionWebDemo NetCore 3.1 ` 
App crash on razor view and throw exception. 
How to fix this please?

https://github.com/51Degrees/device-detection-dotnet/blob/b374090327c2d16a7a35e879db275690719acc2e/FiftyOne.DeviceDetection/Examples/AspNetCore3.1/Views/Home/Index.cshtml#L4

**Comment by Steve51D** [comment]
Hi @kiro64,

Apologies for the delay in getting back to you.
I've not been able to reproduce this error, could you let me know:

- OS platform and version
- IDE
- Did you clone device-detection-dotnet (If so which commit are you on?) or are you copying the example code locally and referencing the FiftyOne.DeviceDetection NuGet package?
- How are you running the example (command line, via IDE, etc)
- A rundown of the steps to get to where you are so I can try and reproduce.

Thanks,
Steve.

**Comment by kiro64** [comment]
Hi @Steve51D 
I figure it out. it is because i was using file `51Degrees-LiteV4.1.hash`  provided in folder `FiftyOne.DeviceDetection\device-detection-cxx\device-detection-data`

It's work now when i try with my company license file. 
You may closed the case, thank you.

**Comment by Steve51D** [comment]
Great, thanks for letting us know.
