### ISSUE TITLE
Tac Intelligence service

### ISSUE THREAD

**Issue by Megatronic1** [51Degrees/device-detection-dotnet#6]
Hello Good Day
I am doing a demo for TAC  intelligence service with C#.
But Im getting this error

'Failed to load aspect properties for element 'hardware'. This is because your resource key does not include access to any properties under 'hardware'.

I am trying to use these Resource keys for the demo.  I selected the property HardwareVendor and HardwareModel.
AQTJih7vx8Sml9Mi2Ug or AQTJih7v-a4hFtAi2Ug

 Do I need a special resource key with privileges??

Im using this code, I get it from 51degrees website

using FiftyOne.DeviceDetection.Cloud.Data;
using FiftyOne.DeviceDetection.Cloud.FlowElements;
using FiftyOne.DeviceDetection.Shared;
using FiftyOne.Pipeline.CloudRequestEngine.FlowElements;
using FiftyOne.Pipeline.Core.FlowElements;
using GettingStarted;
using Microsoft.Extensions.Logging;
using System;
using System.Net.Http;
namespace FiftyOne.DeviceDetection.Examples.Cloud.TacLookup
{
    public class Program
    {
        public class Example
        {
            private static string TAC = "35925406";
            private static string TAC2 = "86386802";
            public void Run(string resourceKey, string cloudEndPoint = "")
            {
                Console.WriteLine("This example shows the details of devices " +
                    "associated with a given 'Type Allocation Code' or 'TAC'.");
                Console.WriteLine("More background information on TACs can be " +
                    "found through various online sources such as Wikipedia: " +
                    "https://en.wikipedia.org/wiki/Type_Allocation_Code");
                Console.WriteLine("----------------------------------------");
                ILoggerFactory loggerFactory = new LoggerFactory();
                HttpClient httpClient = new HttpClient();
                // Create a cloud request engine builder
                var cloudRequestEngineBuilder = new CloudRequestEngineBuilder(loggerFactory, httpClient)
                    .SetResourceKey(resourceKey);
                // If a cloud endpoint has been provided then set the
                // cloud pipeline endpoint. 
                if (string.IsNullOrWhiteSpace(cloudEndPoint) == false)
                {
                    cloudRequestEngineBuilder.SetEndPoint(cloudEndPoint);
                }
                // Create the cloud request engine
                using (var cloudEngine = cloudRequestEngineBuilder.Build())
                // Create the property-keyed engine to process the 
                // response from the request engine.
                using (var propertyKeyedEngine = new HardwareProfileCloudEngineBuilder(loggerFactory)
                    .Build())
                // Create the pipeline using the engines.
                using (var pipeline = new PipelineBuilder(loggerFactory)
                    .AddFlowElement(cloudEngine)
                    .AddFlowElement(propertyKeyedEngine)
                    .Build())
                {
                    // Pass a TAC into the pipeline and list the matching devices.
                    AnalyseTac(TAC, pipeline);
                    AnalyseTac(TAC2, pipeline);
                }
            }
            static void AnalyseTac(string tac, IPipeline pipeline)
            {
                // Create the FlowData instance.
                using (var data = pipeline.CreateFlowData())
                {
                    // Add the TAC as evidence.
                    data.AddEvidence(Constants.EVIDENCE_QUERY_TAC_KEY, tac);
                    // Process the supplied evidence.
                    data.Process();
                    // Get result data from the flow data.
                    var result = data.Get<MultiDeviceDataCloud>();
                    Console.WriteLine($"Which devices are associated with the TAC '{tac}'?");
                    foreach (var device in result.Profiles)
                    {
                        var vendor = device.HardwareVendor;
                        var name = device.HardwareName;
                        var model = device.HardwareModel;
                        // Check that the properties have values.
                        if (vendor.HasValue &&
                            model.HasValue &&
                            name.HasValue)
                        {
                            Console.WriteLine($"\t{vendor.Value} {string.Join(",", name.Value)} ({model.Value})");
                        }
                        else
                        {
                            Console.WriteLine(vendor.NoValueMessage);
                        }
                    }
                }
            }
        }
        static void Main(string[] args)
        {

            // Obtain a resource key for free at https://configure.51degrees.com
            // Make sure to include the 'HardwareVendor' and 'HardwareModel' 
            // properties as they are used by this example.
            //string resourceKey = "AQTJih7v-a4hFtAi2Ug";
            string resourceKey = "AQTJih7vx8Sml9Mi2Ug";

            if (resourceKey.StartsWith("!!"))
            {
                Console.WriteLine("You need to create a resource key at " +
                    "https://configure.51degrees.com and paste it into the code, " +
                    "replacing !!YOUR_RESOURCE_KEY!!.");
                Console.WriteLine("Make sure to include the 'HardwareVendor', " +
                    "'HardwareName' and 'HardwareModel' properties as they " +
                    "are used by this example.");
            }
            else
            {
                new Example().Run(resourceKey);
            }

            Console.WriteLine("Done. Press any key to exit.");
            Console.ReadKey();

        }
    }
}

![screen1](https://user-images.githubusercontent.com/85232701/120482472-cdb9df80-c376-11eb-8b49-0c9ea7da4845.png)

https://51degrees.com/documentation/4.2/_info__resourcekeys.html

![screen2](https://user-images.githubusercontent.com/85232701/120482883-3012e000-c377-11eb-97ef-4a7290d3cb1d.png)

**Comment by ben51degrees** [comment]
@Megatronic1 This should be a quick fix. When you create your resource key, you will need to select the `TAC` and `profiles` properties in addition to the properties you want to return.

I've tried to make it a bit clearer on our documentation, as this isn't obvious. Doesn't seem like that change is live yet, so I will make sure that goes up soon.

Additionaly, you will need to enter a TAC license key when creating the resource key. If you don't already have one, you can obtain one from [here](https://51degrees.com/pricing).

With the resource keys page, the actual URL is `https://51degrees.com/documentation/4.2/_info__resource_keys.html`.  So our warning is missing an underscore. Thanks for bringing that to our attention, and I'll add that change to the code soon.

**Comment by Megatronic1** [comment]
Hi Sir.
I realized something is worng with the resource key.  I have to say I installed the packages to run the app

Can you send me a valid resource key just for test. ?

I follow the steps to get it but something is wrong. Cause I selected the properties and appears the commented error.
Its just for test the tac intelligence service. before to get an account.
 
**Can you help me to check whats worng with these keys?  or Can you share with me a valid key for test?**
I am trying to use these Resource keys for the demo. I selected the property HardwareVendor and HardwareModel.
https://configure.51degrees.com/AQTJih7vx8Sml9Mi2Ug
https://configure.51degrees.com/AQTJih7v-a4hFtAi2Ug

Thanks

**Comment by ben51degrees** [comment]
Hi @Megatronic1 ,
If you follow this link https://configure.51degrees.com/8jrqZ2Sq all the properties you require will be preselected. You'll then just need to add your license key in the details step.
Thanks,
Ben.

**Comment by Megatronic1** [comment]
Hello 
Im still getting the error?
I added the free key. It's posible to do this test with a free key?


![screen4](https://user-images.githubusercontent.com/85232701/120717563-60e53900-c48d-11eb-8c06-7edd25284584.png)

**Comment by ben51degrees** [comment]
Hi @Megatronic1 ,
I don't believe the TAC property is available with a free key. I will get someone more knowledgable on the licensing to contanct you privately to discuss.
